<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Version>0.2.0</Version>
    <AssemblyVersion>26.8.27.6</AssemblyVersion>
    <FileVersion>26.8.27.6</FileVersion>
    <StartupObject>VideoDownloader.Program</StartupObject>
    <Copyright>APPIT Adam Skowroński</Copyright>
    <Authors>APPIT</Authors>
    <ApplicationIcon>Resources\VideoDownloader.ico</ApplicationIcon>
    <PackageIcon>VideoDownloader.ico</PackageIcon>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="Resources\VideoDownloader.ico" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\LICENSE">
      <Link>LICENSE</Link>
    </None>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="YoutubeDLSharp" Version="1.2.0" />
  </ItemGroup>

  <ItemGroup>
    <None Update="Resources\VideoDownloader.ico">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\VideoDownloader.Core\VideoDownloader.Core.csproj" />
  </ItemGroup>

  <Target Name="PostBuild" AfterTargets="PostBuildEvent">
    <Exec Command="xcopy &quot;$(SolutionDir)ExternalLib\*.exe&quot; &quot;$(TargetDir)&quot; /Y /I" />
  </Target>

</Project>